name: 'Squads program upgrade'
description: 'Github action to deploy a squads program upgrade on Solana'
author: 'Cardinal Labs'
branding:
  icon: 'upload'
  color: 'red'
inputs:
  network-url:
    description: 'The Solana network'
    required: true
    default: 'devnet'
  program-multisig:
    description: 'The program multisig authority'
    required: true
  program-id:
    description: 'The program id to upgrade'
    required: true
  program-index:
    description: 'The program index to upgrade'
    required: true
  buffer:
    description: 'The buffer where the program is uploaded to'
    required: true
  spill-address:
    description: 'The program multisig authority'
    required: true
  authority:
    description: 'The upgrade authority'
    required: true
  name:
    description: 'The name of this upgrade'
    required: true
  idl-buffer:
    description: 'The IDL buffer to upgrade for the corresponding program'
    required: false
  authority-index:
    description: 'The index that the authority key is in this multisig (defaults to 1)'
    required: false
  keypair:
    description: 'The keypair to use for deploys'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
