version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race -coverprofile={{ coverage_report_file }} -covermode=atomic -v ./...
      - codecov/upload:
        file:  {{ coverage_report_file }}
              
