version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "54:0a:dd:d8:d1:ac:94:69:18:61:80:9f:90:28:b7:86"
      - checkout
      - run: go install github.com/mgechev/revive
      - run: revive -config revive.toml
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - run:
          name: Upload Code Coverage Report
          command: |
            go get github.com/mattn/goveralls
            goveralls -coverprofile=coverage.txt
