version: 2.1

orbs:
  toolkit: storytel/toolkit@1

parameters:
  go-version:
    type: string
    default: "1.19"

workflows:
  ci:
    jobs:
      - toolkit/go-ci:
          context: gcloud-storytel-build
          version: <<pipeline.parameters.go-version>>
          revive: false
          test_package: ./...
          filters:
            branches:
              ignore: main
          name: ci-pr-branch
          sonarqube_mode: pr

      - toolkit/go-ci:
          context: gcloud-storytel-build
          version: <<pipeline.parameters.go-version>>
          revive: false
          test_package: ./...
          filters:
            branches:
              only: main
          name: ci-base-branch
          sonarqube_mode: base