version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - run: revive -config revive.toml
      - run: bash <(curl -s https://codecov.io/bash)
