# Generated by Django 3.1.3 on 2020-12-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20201217_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
