# Generated by Django 3.1.3 on 2020-12-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statements_pdf',
            field=models.FileField(upload_to='C:\\Users\\rodri\\Documents\\banking-system-masternewudpate\\banking-system-master2\\media'),
        ),
    ]
