# Generated by Django 3.1.3 on 2021-01-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20201230_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statements_pdf',
            field=models.FileField(upload_to='D:\\Mov\\banking-system-master2\\media'),
        ),
    ]
