# Generated by Django 3.1.3 on 2021-01-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20210108_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statements_pdf',
            field=models.FileField(upload_to='C:\\Users\\User\\Desktop\\banking-system-master-3\\media'),
        ),
    ]
